# github workflow名字
name: my first workflow
# 如何去控制workflow触发的trigger
# workflow可以手动去出发
on: workflow_dispatch

jobs:
  # job名字
  build_on_linux:
    # 运行的环境
    runs-on: ubuntu-latest
    # 具体的step
    steps:
      - name: Run a one-line script
        run: |
          echo "hello world!"
      - name: Run a multi-line script
        # |表示后面有多行的命令要去执行
        run: |
          echo "hello github actions"
          date1
  
  build_on_windows:
    runs-on: windows-latest
    if: ${{ success() }}
    needs: [build_on_linux]
    steps:
      - name: Run a multi-line script
        run: |
          echo "hello github actions"
          Get-Date

